services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 9292:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  static-file-server:
    image: halverneus/static-file-server:latest
    container_name: static-file-server
    volumes:
      - ./downloads:/web
    ports:
      - 8080:8080
    restart: unless-stopped

