version: '3.8'

x-volumes:
  &config-path ./data
  &downloads-path ./downloads
  &watch-path ./watch

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - *config-path:/config
      - *downloads-path:/downloads
      - *watch-path:/watch
    ports:
      - 9292:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  static-file-server:
    image: halverneus/static-file-server:latest
    container_name: static-file-server
    volumes:
      - *downloads-path:/web
    ports:
      - 8080:8080
    restart: unless-stopped
