services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${DATA_DIR_PATH:-./data}:/config"
      - "${DOWNLOAD_DIR_PATH:-./downloads}:/downloads"
      - "${WATCH_DIR_PATH:-./watch}:/watch"
    ports:
      - 9292:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  static-file-server:
    image: halverneus/static-file-server:latest
    container_name: static-file-server
    volumes:
      - "${DOWNLOAD_DIR_PATH:-./downloads}:/web"
    ports:
      - 8080:8080
    restart: unless-stopped

